; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; la plateforme décide de la version du framework
; platform = espressif32@6.9.0
;        │
;        ├── framework-arduinoespressif32 2.0.17
;        ├── toolchain-xtensa-esp32
;        ├── esptool
;        ├── LittleFS
;        └── ...

; Commandes utiles :
  ; pio --version       Version de PlatformIO
  ; pio pkg list        Versions des packages installés
  ; pio system info     Résumé complet de l'environnement

[platformio]
;IMPORTANT: En cas d'ajout d'un nouvel environnement,
; ne pas oublier de l'inclure aussi dans 'PinDefinitionsAndMore.h'
default_envs = freenove_esp32s3_wroom_fnk0082_maya      ; Plateforme de test maya
;default_envs = dfrobot_firebeetle2_esp32e_dfr0654      ; Prototype
;default_envs = dfrobot_firebeetle2_esp32e_dfr1139      ; Telecommande  N°1
;default_envs = dfrobot_firebeetle2_esp32s3_dfr0975

; --------------------------------------------
;           Environnement commun
; --------------------------------------------
[env]
;platform = raspberrypi
;framework = arduino
monitor_speed = 115200
;monitor_port  = COM5            ; directory for usb-over-serial 

; --- FLAGS GLOBALES pour forcer C++17 --- (pour tous les environnements)
build_unflags =
    -std=gnu++11
    -std=c++11
    -std=gnu++14
    -std=c++14
build_flags =
    -DCONFIG_OMOTE_LOG_DEFAULT_LEVEL=OMOTE_LOG_LEVEL_VERBOSE  ;-DCONFIG_OMOTE_LOG_DEFAULT_LEVEL=OMOTE_LOG_LEVEL_WARN
    -std=gnu++17

; --- Dépendances communes ---
lib_deps = 
	crankyoldgit/IRremoteESP8266@2.8.6
    bblanchon/ArduinoJson@7.1.0
	;johboh/nlohmann-json@^3.11.3
    ;rzeldent/micro-miniz@^1.0.0
	;tobozo/ESP32-targz@^1.2.9
	;tobozo/ESP32-targz@^1.2.9

; --------------------------------------------
;    Environnement spécifiques par cartes
; --------------------------------------------
[env:freenove_esp32s3_wroom_fnk0082_maya]
platform = espressif32@6.13.0 ;espressif32 ;espressif32@^6.13.0
framework = arduino ; Normaly version language is C++11
board = freenove_esp32_s3_wroom ;esp32-s3-devkitc-1 ;board = esp32-s3-devkitm-1 ;freenove_esp32_s3_wroom
build_flags =
    ${env.build_flags}
    -DMAYA_FREENOVE_ESP32_S3_WROOM_FNK0082
    -DUSE_LITTLEFS ; or -DUSE_SPIFFS
    ;-D ARDUINO_USB_MODE=1
    ;-D ARDUINO_USB_CDC_ON_BOOT=1	  ; To active native Serial but wake up is breaked in this mode !.
    ;-D ARDUINO_HW_CDC_ON_BOOT=1
;monitor_port  = COM11            ; directory for usb-over-serial 
;upload_port = COM11
;monitor_rts = 0 ou 1
;monitor_dtr = 0 ou 1

[env:dfrobot_firebeetle2_esp32e_dfr0654]
platform = espressif32@6.9.0 ;espressif32
framework = arduino ; Normaly version language is C++11
board = dfrobot_firebeetle2_esp32e ;esp32dev
board_build.partitions = huge_app.csv ; Attention: on peut perdre les fichiers dans Filesystem si on change les adresses de cette partition
build_flags =
    ${env.build_flags}
    -DMAYA_DFROBOT_FIREBEETLE2_ESP32E_DFR0654
    -DUSE_LITTLEFS ; or -DUSE_SPIFFS

[env:dfrobot_firebeetle2_esp32e_dfr1139]
platform = espressif32@6.9.0 ;espressif32
framework = arduino ; Normaly version language is C++11
board = firebeetle32 ;esp32dev ;dfrobot_firebeetle2_esp32e
;board_build.flash_size = 16MB
board_build.partitions = large_spiffs_16MB.csv ;huge_app.csv 
build_flags =
    ${env.build_flags}
    -DMAYA_DFROBOT_FIREBEETLE2_ESP32E_DFR1139
    -DUSE_LITTLEFS ; or -DUSE_SPIFFS

[env:dfrobot_firebeetle2_esp32s3_dfr0975]
platform = espressif32@6.9.0 ;espressif32
framework = arduino ; Normaly version language is C++11
;board = esp32-s3-devkitc-1
;board = esp32-s3-devkitm-1
board = dfrobot_firebeetle2_esp32s3
build_flags =
    ${env.build_flags}
    -DMAYA_DFROBOT_FIREBEETLE2_ESP32S3_DFR0975
    -DUSE_LITTLEFS ; or -DUSE_SPIFFS

[env:pico]
platform = raspberrypi
framework = arduino
board = pico
build_flags =
    ${env.build_flags}
    -DUSE_LITTLEFS ; or -DUSE_SPIFFS
;monitor_port  = COM5            ; directory for usb-over-serial 
;upload_port = E:
;lib_deps = z3t0/IRremote@^4.4.0

;[env:raspberry-pi-pico]
;platform = wizio-pico
;board = raspberry-pi-pico
;framework = baremetal

;upload_port  = /media/devcon/RPI-RP2/   ; directory for mass-storage
;monitor_port  = /dev/ttyACM0            ; directory for usb-over-serial 
;monitor_speed = 115200
;board_build.bynary_type = copy_to_ram   
;build_flags = -D PICO_STDIO_USB              ; enable stdio over USB  
;build_unflags  = -D PICO_STDIO_UART 
